apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: litmus
  labels:
    app: nginx
  annotations:
    litmuschaos.io/chaos: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: litmus
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
